[package]
name = "rustrace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.101"
image = "0.25.9"
mimalloc = "0.1.48"
rand = "0.9.0"
rayon = "1.10.0"

# [profile.release]
# debug = "line-tables-only"
